<a href="https://colab.research.google.com/github/MinThuKhant763/machine-learning/blob/main/Pandas_with_real_dataset_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import pandas as pd
import numpy as np
data = {"Name":["Aung","Chaw","Su","JuJu","Hla","Moe","Kay"],
        "City":["Ygn","Kalaw","Ygn","Mdy","Kalaw","Ygn","Mdy"],
        "Age":[25,35,30,28,22,45,32],
        "Salary":[30000,45000,38000,49000,50000,20000,60000]}
df = pd.DataFrame(data)
print(df)

   Name   City  Age  Salary
0  Aung    Ygn   25   30000
1  Chaw  Kalaw   35   45000
2    Su    Ygn   30   38000
3  JuJu    Mdy   28   49000
4   Hla  Kalaw   22   50000
5   Moe    Ygn   45   20000
6   Kay    Mdy   32   60000

In [36]:
df.groupby("City")["Salary"].mean()

City
Kalaw    47500.000000
Mdy      54500.000000
Ygn      29333.333333
Name: Salary, dtype: float64

In [37]:
df.groupby("City")["Name"].count()

City
Kalaw    2
Mdy      2
Ygn      3
Name: Name, dtype: int64

In [38]:
df.groupby("City")["Age"].max()

City
Kalaw    35
Mdy      32
Ygn      45
Name: Age, dtype: int64

In [39]:
df.describe()

             Age        Salary
count   7.000000      7.000000
mean   31.000000  41714.285714
std     7.527727  13474.844287
min    22.000000  20000.000000
25%    26.500000  34000.000000
50%    30.000000  45000.000000
75%    33.500000  49500.000000
max    45.000000  60000.000000

In [40]:
df["Salary"].describe()

count        7.000000
mean     41714.285714
std      13474.844287
min      20000.000000
25%      34000.000000
50%      45000.000000
75%      49500.000000
max      60000.000000
Name: Salary, dtype: float64

In [41]:
df["Age"].mean()

np.float64(31.0)

In [42]:
df["Salary"].min(),df["Salary"].max()

(20000, 60000)

In [43]:
data1 = {"Name":["Aung","Chaw","Hla","Moe","Kyaw"],
        "Age":[25,np.nan,28,np.nan,35],
        "Salary":[30000,45000,np.nan,50000,np.nan],
        "City":["Ygn","Kalaw",None,"Mdy","Ygn"]}
df1 = pd.DataFrame(data1)
print(df1)

   Name   Age   Salary   City
0  Aung  25.0  30000.0    Ygn
1  Chaw   NaN  45000.0  Kalaw
2   Hla  28.0      NaN   None
3   Moe   NaN  50000.0    Mdy
4  Kyaw  35.0      NaN    Ygn

In [44]:
#fill data if null data
df1["Age"].fillna(df1["Age"].mean())

0    25.000000
1    29.333333
2    28.000000
3    29.333333
4    35.000000
Name: Age, dtype: float64

In [45]:
#drop data if null value
df1.dropna(subset=["Salary"],inplace=True)
print(df1)

   Name   Age   Salary   City
0  Aung  25.0  30000.0    Ygn
1  Chaw   NaN  45000.0  Kalaw
3   Moe   NaN  50000.0    Mdy