<a href="https://colab.research.google.com/github/MinThuKhant763/machine-learning/blob/main/Pandas_with_real_dataset_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd
df = pd.DataFrame({"Name":["Aung","Su","May","Hla"],
        "Age":[20,21,24,23],
        "Salary":[30000,50000,60000,40000]})
print(df)

   Name  Age  Salary
0  Aung   20   30000
1    Su   21   50000
2   May   24   60000
3   Hla   23   40000

In [6]:
df[(df["Age"]>=22)&(df["Age"]<=30)]

  Name  Age  Salary
2  May   22   50000
3  Hla   23   60000

In [7]:
df[df["Salary"]!=30000]

  Name  Age  Salary
1   Su   21   40000
2  May   22   50000
3  Hla   23   60000

In [11]:
df.sort_values("Age")

   Name  Age  Salary
0  Aung   20   30000
1    Su   21   40000
3   Hla   23   60000
2   May   24   50000

In [14]:
df.sort_values("Salary")

   Name  Age  Salary
0  Aung   20   30000
3   Hla   23   40000
1    Su   21   50000
2   May   24   60000

In [15]:
df.sort_values("Salary",ascending=False)

   Name  Age  Salary
2   May   24   60000
1    Su   21   50000
3   Hla   23   40000
0  Aung   20   30000

In [16]:
df.sort_values(["Age","Salary"],ascending=[True,False])

   Name  Age  Salary
0  Aung   20   30000
1    Su   21   50000
3   Hla   23   40000
2   May   24   60000